apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springdemo
  template:
    metadata:
      labels:
        app: springdemo
    spec:
      containers:
        - name: springtransactional
          image: badrinathwrk/springdemo:springdemo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          imagePullPolicy: Always


apiVersion: v1
kind: Service
metadata:
  name: springdemo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springdemo
