apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springdemo
  template:
    metadata:
      labels:
        app: springdemo
    spec:
      containers:
        - name: springtransactional
          image: badrinathwrk/springdemo:springdemo
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
          imagePullPolicy: Always


apiVersion: v1
kind: Service
metadata:
  name: springdemo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: springdemo
